services:
  - type: web
    name: health-translation
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: GROQ_API_KEY
        value: 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
